version: '3.3'

services: 
  postgres:
    image: postgres:12.9
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: qweasd123      
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '5'

  api:
    image: b3control/api:0.1.0
    restart: always
    environment:
      DB_HOST: 'postgres'
      DB_PORT: '5432'
      DB_USER: 'postgres'
      DB_PASSWORD: 'qweasd123'
      DB_NAME: 'b3control_current'
    ports:
      - '4000:4000'
    logging:
      driver: json-file
      options:
        max-size: 20m
        max-file: '5'

volumes:
  postgres-volume:

networks:
  default: